PartsUnlimited/src/PartsUnlimitedWebsite/Controllers/StoreController.cs
// Copyright (c) Microsoft. All rights reserved.
// Licensed under the MIT license. See LICENSE file in the project root for full license information.

using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Caching.Memory;
using PartsUnlimited.Models;
using System;
using System.Linq;

namespace PartsUnlimited.Controllers
{
    public class StoreController : Controller
    {
        private readonly IPartsUnlimitedContext _db;
        private readonly IMemoryCache _cache;

        public StoreController(IPartsUnlimitedContext context, IMemoryCache memoryCache)
        {
            _db = context;
            _cache = memoryCache;
        }

        //
        // GET: /Store/

        public IActionResult Index()
        {
            var category = _db.Categories.ToList();

            return View(category);
        }

        //
        // GET: /Store/Browse?category=Brakes

        public IActionResult Browse(int categoryId)
        {
            // Retrieve Category category and its Associated associated Products products from database

            // TODO [EF] Swap to native support for loading related data when available
            var categoryModel = _db.Categories.Single(g => g.CategoryId == categoryId);
            categoryModel.Products = _db.Products.Where(a => a.CategoryId == categoryModel.CategoryId).ToList();

            return View(categoryModel);
        }

        public IActionResult Details(int id)
        {
            Product productData;

            productData = _db.Products.Single(a => a.ProductId == id);
            productData.Category = _db.Categories.Single(g => g.CategoryId == productData.CategoryId);


            return View(productData);
        }
    }
}

PartsUnlimited/src/PartsUnlimitedWebsite/Views/Shared/Components/Announcement/Default.cshtml
@model PartsUnlimited.Models.Product

<div class="alert alert-new-arrival @(@Model == null ? "hidden": "show") " id="alert-new-arrival" role="alert">
    <div class="container">
        <div class="alert-content">
            <span class="glyphicon glyphicon-bullhorn"></span>
            @if (Model == null)
            {
                <a id="new-arrival" href="#"></a>
            }
            else
            {
                <a id="new-arrival" href="@Url.Action("Details", "Store", new { id = Model.ProductId })">@string.Format(" New Arrival : {0}", Model.Title)</a>
            }
        </div>
    </div>
</div>